import { createClient } from '@/prismicio';
import { getClient } from '@/services/client';
import { Footer } from '../../devlink/Footer';
import "../../devlink/global.css";
import { getSettings } from '@/services/queries';
import { FooterLink } from '~/devlink';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { data } = await getClient().query({ query: getSettings });
  const settings = data.navigationCollection.items[0];

  return (
    <html lang="en">
      <body>
        {children}
        <Footer
          description={settings.aboutText}
          // generalInquiries={settings.address.json}
          // address={settings.getInTouchInfo.json}
          menuSlot={settings.footerMenuCollection.items.map((link, index) => {
            return <FooterLink key={index} label={link.title} />
          })}
          legalMenuSlot={
            settings.footerLegalMenuCollection.items.map((link, index) => {
              return <FooterLink key={index} label={link.title}>
              </FooterLink>
            })
          }
        />
      </body>

    </html>
  );
}
