import { PrismicPreview } from '@prismicio/next'
import { createClient, repositoryName } from '@/prismicio'
import { Navbar, NavbarLink } from "../../devlink";
import "../../devlink/global.css";
import { Footer } from '../../devlink/Footer';
import { FooterLink } from '../../devlink/FooterLink';
import { FooterLinkLegal } from '../../devlink/FooterLinkLegal';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const client = createClient();

  const menu = await client.getSingle("main_navigation");
  const footer = await client.getSingle("footer");
  
  return (
    <html lang="en">
      <body>

        <Navbar navbarLeftSlot={
          menu.data.menu_items.map((link, index) => (
            <NavbarLink key={index} label={link.label} link={link.link.url}>
            </NavbarLink>
          ))
        }></Navbar>
        {children}
        <PrismicPreview repositoryName={repositoryName} />

        <Footer
          footerMenuLegalSlot={
            footer.data.legal_links.map((link, index) => (
              <FooterLinkLegal key={index} label={link.label} link={link.link.url}>
              </FooterLinkLegal>
            ))
          }

          footerMenuSlot={
            footer.data.links.map((link, index) => {
              console.log(link.link.url);
              return <FooterLink key={index} label={link.label} link={link.link.url}>
              </FooterLink>
            })
          } meta={"add me to the cms"} />
      </body>

    </html>
  );
}
