// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  collection_slider: dynamic(() => import("./CollectionSlider")),
  content_cta: dynamic(() => import("./ContentCta")),
  hero_home: dynamic(() => import("./HeroHome")),
};
